# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ihorhrysha
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.0.1
  arch: amd64

secret:
  name: gobot
  key: token
  value: ""
  env: TELE_TOKEN

volumes:
- name: dev-mem
  hostPath:
    path: /dev/mem
    type: ""

volumeMounts:
- mountPath: /dev/mem
  name: dev-mem

autoscaling:
  enabled: false

podAnnotations: {}

imagePullSecrets: {}

securityContext: {}

podSecurityContext: {}


