name: GOBOT-CICD

on:
  push:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        run: make test

      - name: Login to github container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: release
        run: make release REGISTRY="ghcr.io/ihorhrysha"

      - name: Clean
        run: make clean REGISTRY="ghcr.io/ihorhrysha"
