name: GOBOT-CICD

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2
    
    - name: Test
      run: make test
            # - name: "Set up Go"
            #     uses: actions/setup-go@v2
            #     with:
            #         go-version: 1.x

            # - name: Build
            #     run: go build

            # - name: Test
            #     run: go test ./...

            # - name: Deploy
            #     uses: peaceiris/actions-gh-pages@v3
            #     with:
            #         github_token: ${{ secrets.GITHUB_TOKEN }}
            #         publish_dir: ./public