name: GOBOT-CICD

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        run: make test

      - name: "Login to docker hub"
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Release
        env:
          APP: "gobot"
          REGISTRY: ${{ env.DOCKERHUB_USERNAME }}
        run: make release
        
        #image push TARGETARCH=$TARGETARCH

      # - name: Clean
      #   run: make clean TARGETARCH=$TARGETARCH

            # - name: "Set up Go"
            #     uses: actions/setup-go@v2
            #     with:
            #         go-version: 1.x

            # - name: Build
            #     run: go build

            # - name: Test
            #     run: go test ./...

            # - name: Deploy
            #     uses: peaceiris/actions-gh-pages@v3
            #     with:
            #         github_token: ${{ secrets.GITHUB_TOKEN }}
            #         publish_dir: ./public