name: GOBOT-CICD

env:
  TARGETARCH: amd64
  TARGETOS: linux
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.actor }}/gobot

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  packages: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        run: make test

      - name: Login to github container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: release
        run: make release REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY TARGETARCH=$TARGETARCH TARGETOS=$TARGETOS

      - name: Clean
        run: make clean REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY TARGETARCH=$TARGETARCH TARGETOS=$TARGETOS

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: echo "VERSION=$(make version)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION) | .image.registry=strenv(REGISTRY)  | .image.repository=strenv(REPOSITORY) | .image.arch=strenv(TARGETARCH)| .image.os=strenv(TARGETOS)' helm/values.yaml
    
    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.appVersion=strenv(VERSION)' helm/Chart.yaml

    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push